config/routes.rb
Rails.application.routes.draw do

  
  get '/weather' => 'weather#forecast'
  
  resources :posts
  resources :users
  resources :comments, except: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]

  root 'posts#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  validates_presence_of :user
  validates_presence_of :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
    	DRIVING_AGE_LIMIT = 16
    	
    has_secure_password

    def full_name
		"#{first_name} #{last_name}"
	end

	def can_drive?
		age >= DRIVING_AGE_LIMIT
		
	has_many :posts
	has_many :comments
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate
  
  def authenticate
    if session[:current_user_id]
      @current_user = User.find(session[:current_user_id])
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]


  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

      if @comment.save
        redirect_to post_path(@comment.post), notice: 'Comment was successfully created.'
      else
        render :new
      end
    end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
      if @comment.update(comment_params)
        redirect_to post_path(@comment.post), notice: 'Comment was successfully updated.' }
      else
        render :edit
      end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      redirect_to post_path(@comment.post), notice: 'Comment was successfully deleted.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :load_post, only: [:show, :edit, :update, :destroy]
    before_action :require_author, only: [:edit, :update, :destroy]

    def index
        @posts = Post.all
    end
    
    def show
     @comments = @post.comments
     @comment = Comment.new(post: @post)
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new post_params
        
        if @post.save
            redirect_to post_path(@post)
        else
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @post.update post_params
            redirect_to post_path(@post)
        else
            render :edit
        end
    end
    
    def destroy
        @post.destroy
        redirect_to root_path
    end
    
    private
    
    def load_post
       @post = Post.find params[:id]
    end
    
    def post_params
     params.require(:post).permit(:title, :body)
    end
    
    def require_author
        if !@current_user || @post.user_id != @current_user.id
            redirect_to post_path(@post), alert: "You can only edit your own posts."
        end
    end
     
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   
   # Sign-in form
   def new
   end
    
    # Submitting the sign-in form
    def create
        # Require email and paossword params
        if params[:email].blank? || params[:password].blank?
            flash[:alert] = "Email and password required"
            render :new 
            return
        end
        
        # Ensure that a user exists for that email
        user = User.find_by email: params[:email]

        if user.present?
            if user.authenticate(params[:password])
                session[:current_user_id] = user.id
                redirect_to root_path, notice: "Welcome back, #{user.first_name}!"
            else
              flash[:alert] = "Email/password not found"
              render :new
            end
    
        else
            flash[:alert] = "Email/password not found"
            render :new
        end
    end

    
    # Logging out
    def destroy
        session[:current_user_id] = nil
        redirect_to root_path, notice: "Good-bye for now"
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
    
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :age)
    end
end

app/controllers/weather_controller.rb
require 'net/http'

class WeatherController < ActionController::Base

    def forecast
        lat = params[:lat]
        lng = params[:lng]
        
        json = Rails.cache.fetch('forecast:#{lat},#{lng}', expires_in: 15.minutes) do
            uri = URI.parse("https://api.darksky.net/forecast/#{Rails.application.secrets.darksky_api_key}/37.8267,-122.4233")
            http = Net::HTTP.new(uri.host, uri.port)
            http.use_ssl = true
            http.get(uri.request_uri).body
         end
         
         @data = JSON.parse(json, symbolize_names: true)
         @currently = @data[:currently]
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="mb-4 navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "My Blog!", root_path, class: "navbar-brand" %>
`     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">`
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to users_path, class: "nav-link" do %>
              Users
              <% if request.path == users_path %>
                <span class="sr-only">(current)</span>
              <% end %>
            <% end %>
          </li>
        </ul>
        <div class="ml-auto">
          <% if @current_user.present? %>
            <span class="dropdown">
              <a class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">
                <%= @current_user.full_name %>
                <span class="caret"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                <%= link_to "Profile", user_path(@current_user), class: "dropdown-item" %>
                <%= link_to "Posts", posts_path, class: "dropdown-item" %>
                <div class= "dropdown-divider"></div>
                <%= link_to "Logout", session_path(@current_user), method: :delete, class: "dropdown-item" %>
              </div>
            </span>

            <%= link_to 'Add post', new_post_path, class: "btn btn-primary" %>
          <% else %>
            <%= link_to 'Login', new_session_path, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="row">
       <div class="col-sm-10">
        <% if notice %>    
          <div class="alert alert-success" role="alert">
            <%= notice %>
          </div>
        <% end %>
    
        <% if alert %>
          <div class="alert alert-danger" role="alert">
            <%= alert %>
          </div>
        <% end %>
        
        <%= yield %>
                
      </div>
      <div class="col-sm-2">
        <div id="weather"><!--This content will be loaded async --></div>
        
        <script>
        if (navigator && navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var coords = position.coords;
            var lat = Math.round(coords.latitude * 10000) / 10000
            var lng = Math.round(coords.longitude * 10000) / 10000
            
           $.get('/weather', { lat: lat, lng: lng }, function(forecastHTML) {
              var weatherContainer = document.getElementById("weather");
              weatherContainer.innerHTML = forecastHTML
            })
          })
        }
        </script>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <div>
        <label>
            Title: <%= f.text_field :title %>
        </label>
    </div>
    <div>
        <label>
            Body: <%= f.text_area :body %>
        </label>
    </div>
    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to "Cancel", post_path(@post) %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="card mb-4 %>"
        <div class="card-body">
          <div class="card-body">
              <h5 class="card-title"><%= post.title -%></h5>
    
    <% if post.user %>
        <h6 class=card-subtitle mb-2 text-muted"><%= post.user.full_name %></h6>
    <% end %>
    
    <p class="card-text"><%= truncate post.body %></p>
    
    <%= link_to "Read more", post_path(post) %>
  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
    <%= @post.body %>
</p>

<p>
    
<%= link_to "All posts", root_path %> - 
<%= link_to "Edit post", edit_post_path(@post) %> - 
<%= link_to "Delete post", post_path(@post), method: :delete %>
</p>

</p>

<p id="notice"><%= notice %></p>

<h3>Comments</h3>

  <% @comments.each do |comment| %>
    <div class="card mb-4">
        <div class="card-body">
          <% if comment.user %>
            <h6 class="card-title mb-2 text-muted"><%= comment.user.full_name %></h6>
          <% end %>
          <p class="card-text"><%= comment.body %></p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
          <div>
            <%= link_to 'Edit', edit_comment_path(comment) %>
            <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
      </div>
    </div>

  <% end %>


<br>

<%= render 'comments/form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/weather/forecast.html.erb
<p>
    <%= @currently[:summary] %> <%= @currently[:temperature] %>
</p>